apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  namespace: heartbeat
  labels:
    app: heartbeat

spec:
  type: NodePort
  selector:
    app: heartbeat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080

---

apiVersion: v1
kind: Pod
metadata:
  name: heartbeat
  namespace: heartbeat
  labels:
    app: heartbeat

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: ghcr.io/cse-labs/heartbeat:beta

    args:
      - --log

    ports:
    - containerPort: 8080

    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 5
      failureThreshold: 10
      periodSeconds: 60
    startupProbe:
      httpGet:
        path: /readyz
        port: http
      initialDelaySeconds: 5
      failureThreshold: 60
      periodSeconds: 2
    resources:
      limits:
        memory: 128Mi
        cpu: 200m
      requests:
        memory: 64Mi
        cpu: 100m
