apiVersion: v1
kind: Pod
metadata:
  name: tinybench
  labels:
    app: tinybench

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: ghcr.io/cse-labs/tinybench:beta

    args:
      - --log

    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: tinybench
  labels:
    app: tinybench

spec:
  type: NodePort
  selector:
    app: tinybench
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
