name: Build tinybench

on:
  schedule:
    # Run Sunday at 6:00 AM UTC
    - cron: "0 6 * * 0"

  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - '**.go'
    - '.github/workflows/build.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      BARTR: ghcr.io/bartr/tinybench
      CSE_LABS: ghcr.io/cse-labs/tinybench

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker pull
      run: |
        docker pull golang:alpine
        docker pull busybox
        
    - name: Docker Build
      run: |
        docker build . -t image
        
    - name: Docker Tag and Push
      run: |

        # tag the image
        docker tag image $BARTR:latest
        docker tag image $BARTR:beta

        # tag the image
        docker tag image $CSE_LABS:latest
        docker tag image $CSE_LABS:beta

        # Push to the registries
        docker push -a $BARTR
        docker push -a $CSE_LABS
