name: Build tinybench

on:
  schedule:
    # Run Sunday at 6:00 AM UTC
    - cron: "0 6 * * 0"

  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - '**.go'
    - '.github/workflows/build.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/bartr/tinybench

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker pull
      run: |
        docker pull golang:alpine
        docker pull busybox
        
    - name: Docker Build
      run: |
        docker build . -t image
        
    - name: Docker Tag and Push
      run: |

        # tag the repo
        docker tag image $DOCKER_REPO:latest
        docker tag image $DOCKER_REPO:beta

        # Push to the repo
        docker push -a $DOCKER_REPO
