name: Build Heartbeat

on:
  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - '**.go'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      IMAGE: ghcr.io/bartr/heartbeat
      CSE: ghcr.io/cse-labs/heartbeat

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_ID }}
        password: ${{ secrets.GH_PAT }}

    - name: Docker pull
      run: |
        docker pull golang:alpine
        docker pull busybox
        
    - name: Docker Build
      run: |
        docker build . -t image
        
    - name: Docker Tag and Push
      run: |

        # tag the image
        docker tag image $IMAGE:beta
        docker tag image $CSE:beta

        # Push to the registries
        docker push -a $IMAGE
        docker push -a $CSE
