name: Release Heartbeat

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux,windows]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_ID }}
        password: ${{ secrets.GH_PAT }}

      # add kic CLI to release
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src"
          binary_name: "heartbeat"
          ldflags: "-s -w -X main.Version=0.1.0"

    - name: Docker pull
      run: |
        docker pull golang:alpine
        docker pull busybox
        
    - name: Docker Build
      run: |
        docker build . -t image
        
    - name: Docker Tag and Push
      run: |

        # tag the image
        docker tag image $IMAGE:beta
        docker tag image $IMAGE:latest
        docker tag image $CSE:beta
        docker tag image $CSE:latest

        # Push to the registries
        docker push -a $IMAGE
        docker push -a $CSE
