name: Release Heartbeat

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v2

      # add binary to release
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./src"
          binary_name: "heartbeat"
          ldflags: "-s -w -X main.Version=0.1.0"
